[package]
name = "shuttlings-cch24"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.0.0"
serde = { version = "1.0.215", features = ["derive"] }
shuttle-poem = "0.49.0"
shuttle-runtime = "0.49.0"
tokio = "1.26.0"
